afet-yonetim-sistemi/ays-be

src/main/java/com/ays/backend/config/OpenApiConfig.java
src/main/resources/application.yml
src/main/resources/db/changelog/changes/1-create-info-organization-table-changelog.xml
src/main/resources/db/changelog/changes/2-create-info-user-table-changelog.xml
src/main/resources/db/changelog/changes/3-create-info-user-type-table-changelog.xml

Revised Tables for Liquibase and Swagger Config

Revised Tables for Liquibase and Swagger Config

---

pom.xml
src/main/java/com/ays/backend/mapper/UserMapper.java
src/main/java/com/ays/backend/user/controller/UserController.java
src/main/java/com/ays/backend/user/controller/payload/request/PaginationRequest.java
src/main/java/com/ays/backend/user/service/UserService.java
src/main/java/com/ays/backend/user/service/dto/UserDTO.java
src/main/java/com/ays/backend/user/service/impl/UserServiceImpl.java
src/test/java/com/ays/backend/user/controller/UserControllerTest.java
src/test/java/com/ays/backend/user/model/entities/UserBuilder.java
src/test/java/com/ays/backend/user/service/UserServiceTest.java
src/test/java/com/ays/backend/user/service/dto/UserDTOBuilder.java

What I have done is based on the implementation of all processes shown below.
1 ) Get User process with its controller and service test
2 ) Get User By Id with its controller and service test

Get User(s) Implementation

---

src/main/java/com/ays/backend/config/SecurityConfig.java
src/test/java/com/ays/backend/actuator/ActuatorIntegrationTest.java

What I have done in the security config to give a permission to /actuator to access its features

Permission of Actuator

---

src/main/java/com/ays/admin_user/model/entity/AdminUserEntity.java
src/main/java/com/ays/admin_user/model/enums/AdminRole.java
src/main/java/com/ays/admin_user/model/mapper/AdminUserRegisterRequestToAdminUserEntityMapper.java

Fix Admin Default Role Issue
In the Admin Registration flow, as the mapping of data cannot contain the request to the `ROLE` field in the `AdminUserEntity `object, it is necessary to assign the default value as `ADMIN`. 
- refactor/115/add-admin-default-role …

#115 | Refactor Admin Default Role

---

src/main/java/com/ays/admin_user/model/entity/AdminUserEntity.java
src/main/java/com/ays/auth/model/enums/AysTokenClaims.java

Add institution name to token for Admin User
The `institutionName` information is also included in the information that should be displayed on the Front-End side. If the information is defined in the token, this action can be taken on the FE side. `InstitutionName `information for Admin User must be added to the token.
- Add `INSTITUTION_NAME` to `AysTokenClaims`
- Add `INSTITUTION_NAME` information to Admin through `getClaims `method of `AdminUserEntity`
board or …

#123 | Add institution name to token for Admin User

---

README.md
src/main/java/com/ays/admin_user/model/entity/AdminUserRegisterVerificationEntity.java
src/main/java/com/ays/admin_user/service/impl/AdminUserRegisterServiceImpl.java
src/test/java/com/ays/admin_user/model/entity/AdminUserRegisterVerificationEntityBuilder.java
src/test/java/com/ays/admin_user/service/impl/AdminUserRegisterServiceImplTest.java

The problem of using the Verification ID in the Admin Registration Flow more than once.
#157 "Admin Kayıt Akışındaki Verification ID'nin Birden Fazla Kez Kullanılması"
The problem was solved by throwing an "AysAdminUserRegisterVerificationCodeNotValidException" error when the "verification id" value used during the creation of a new admin is not "AdminUserRegisterVerificationStatus.WAITING". At the end of the related flow, the status of the "AdminUserRegisterVerificationEntity" object associated with the "verification id" is already changed to "AdminUserRegisterVerificationStatus.COMPLETED".
In this way, when the request is sent again with the same verification id value, the "AysAdminUserRegisterVerificationCodeNotValidException" error is thrown because it is …

#157 Admin Registration Flow Bugfix

---

src/main/java/com/ays/assignment/controller/AssignmentController.java
src/main/java/com/ays/assignment/model/dto/request/AssignmentSaveRequest.java
src/main/java/com/ays/assignment/model/dto/request/AssignmentSearchRequest.java
src/main/java/com/ays/assignment/model/dto/response/AssignmentResponse.java
src/main/java/com/ays/assignment/model/dto/response/AssignmentSearchResponse.java
src/main/java/com/ays/assignment/model/entity/AssignmentEntity.java
src/main/java/com/ays/assignment/model/mapper/AssignmentSaveRequestToAssignmentMapper.java
src/main/java/com/ays/assignment/model/mapper/AssignmentToAssignmentResponseMapper.java
src/main/java/com/ays/assignment/model/mapper/AssignmentToAssignmentSearchResponseMapper.java
src/main/java/com/ays/assignment/repository/AssignmentRepository.java
src/main/java/com/ays/assignment/service/AssignmentSearchService.java
src/main/java/com/ays/assignment/service/impl/AssignmentSearchServiceImpl.java
src/main/java/com/ays/assignment/util/exception/AysAssignmentNotExistByLatitudeAndLongitudeException.java
src/main/java/com/ays/assignment/util/exception/AysAssignmentNotExistByPointException.java
src/main/java/com/ays/assignment/util/exception/AysAssignmentUserNotReadyException.java
src/main/java/com/ays/location/model/entity/UserLocationEntity.java
src/main/java/com/ays/location/model/mapper/UserLocationSaveRequestToUserLocationEntityMapper.java
src/main/java/com/ays/location/service/impl/UserLocationServiceImpl.java
src/main/java/com/ays/location/util/AysLocationUtil.java
src/main/java/com/ays/user/model/entity/UserEntity.java
src/main/resources/db/changelog/changes/2-ays-dml.xml
src/test/java/com/ays/AbstractSystemTest.java
src/test/java/com/ays/assignment/controller/AssignmentControllerTest.java
src/test/java/com/ays/assignment/controller/AssignmentSystemTest.java
src/test/java/com/ays/assignment/model/AssignmentBuilder.java
src/test/java/com/ays/assignment/model/dto/request/AssignmentSearchRequestBuilder.java
src/test/java/com/ays/assignment/model/entity/AssignmentEntityBuilder.java
src/test/java/com/ays/assignment/service/impl/AssignmentSearchServiceImplTest.java
src/test/java/com/ays/util/AysTestData.java

Imploement the process of searching Assignment by location
#95  
board (BE …

#95 | Implement the process of searching Assignment by location

---

src/main/java/com/ays/assignment/model/dto/response/AssignmentSearchResponse.java
src/main/java/com/ays/assignment/model/mapper/AssignmentToAssignmentSearchResponseMapper.java

I added location field instead of longitude and latitude fields in AssignmentSearchResponse and updated mapper of AssignmentSearchResponse.
#163 
board or milestone. However, if there is no …

#163 | Fixed response type of search assignment endpoint

---

src/main/java/com/ays/admin_user/controller/AdminUserRegisterApplicationController.java
src/main/java/com/ays/common/model/AysPaging.java
src/main/java/com/ays/common/model/dto/request/AysPagingRequest.java
src/main/resources/application.yml
src/test/java/com/ays/common/model/AysPagingBuilder.java

- Pagination Infrastructure Has Been Refactored and Pagination Validations Have Been Fixed
- `@Valid` Annotation Has Been Added to Parameter of `AdminUserRegisterApplicationController.getRegistrationApplications()` Method
- `@UUID` Annotation Has Been Added to Parameter of `AdminUserRegisterApplicationController.getRegistrationApplicationById()` Method
board (BE Board, In Review column) and milestone to track the progress.
The default project maintainers and team members will be automatically assigned as reviewers for this pull request.

AYS-29 | Pagination Infrastructure Has Been Refactored and Pagination Validations Have Been Fixed

---

src/main/java/com/ays/admin_user/model/mapper/AdminUserEntityToAdminUserMapper.java
src/main/java/com/ays/admin_user/model/mapper/AdminUserRegisterApplicationEntityToAdminUserRegisterApplicationMapper.java
src/main/java/com/ays/admin_user/model/mapper/AdminUserRegisterApplicationToAdminUserRegisterApplicationCreateResponseMapper.java
src/main/java/com/ays/admin_user/model/mapper/AdminUserRegisterApplicationToAdminUserRegisterApplicationResponseMapper.java
src/main/java/com/ays/admin_user/model/mapper/AdminUserRegisterApplicationToAdminUserRegisterApplicationsResponseMapper.java

- Fix the issue not showing phone number info in AdminUserRegisterApplicationResponse by defining map method in AdminUserRegisterApplicationToAdminUserRegisterApplicationResponseMapper
- Add some Java Docs in some mapper classes as they cannot be defined.
- The code is formatted according to the project's coding …

AYS-2 | Fix the issue not showing phone number info in AdminUserRegisterApplicationResponse and Add Some Java Docs in Some Mapper Classes

---

src/main/java/com/ays/common/util/validation/NameValidator.java
src/test/java/com/ays/admin_user/controller/AdminUserRegisterApplicationControllerTest.java
src/test/java/com/ays/assignment/controller/AssignmentControllerTest.java
src/test/java/com/ays/user/controller/UserControllerTest.java

We have revised Regex so that the firstname and the lastname cannot start with special characters.
- Necessary documentation has been added or existing documentation has been updated, specifically …

AYS-142 | Forbid FirstName & LastName To Start With Special Characters

---

src/main/java/org/ays/auth/model/request/AdminRegistrationApplicationListRequest.java
src/main/java/org/ays/common/model/AysSort.java
src/main/java/org/ays/common/model/request/AysPagingRequest.java
src/main/java/org/ays/emergency_application/model/request/EmergencyEvacuationApplicationListRequest.java

AYS-279 | Pageable Validations Have Been Fixed

---

CONTRIBUTING.md

AYS-409 | `CONTRIBUTING.md` File Has Been Improved

---

src/main/java/org/ays/auth/service/impl/AysUserCreateServiceImpl.java

AYS-410 | Value of Temp Value Has Been Changed with Random Text in User Create Flow

---

src/main/java/org/ays/common/util/validation/NoSpecialCharacterValidator.java
src/test/java/org/ays/auth/controller/AdminRegistrationApplicationControllerTest.java
src/test/java/org/ays/emergency_application/controller/EmergencyEvacuationApplicationControllerTest.java

AYS-550 | NoSpecialCharacterValidator Have Been Updated to Prevent Strings from Starting or Ending With Spaces

---

src/main/java/org/ays/common/exception/handler/GlobalExceptionHandler.java
src/main/java/org/ays/common/model/response/AysErrorResponse.java
src/test/java/org/ays/auth/controller/AdminRegistrationApplicationEndToEndTest.java
src/test/java/org/ays/auth/controller/AysRoleControllerTest.java
src/test/java/org/ays/common/model/response/AysErrorResponseBuilder.java

AYS-555 | Refactored "ALREADY EXIST" errors to standardize as "CONFLICT ERROR"

---

src/main/java/org/ays/common/model/AysAuditLog.java
src/main/java/org/ays/common/model/request/AysHttpHeader.java
src/main/java/org/ays/common/model/request/AysPhoneNumberRequest.java
src/main/java/org/ays/common/util/AysJsonUtil.java
src/main/java/org/ays/common/util/AysMaskUtil.java
src/main/java/org/ays/emergency_application/model/request/EmergencyEvacuationApplicationRequest.java

AYS-509 | Restricted Fields Have Been Masked while Saving Logs

---

src/main/java/org/ays/common/exception/handler/GlobalExceptionHandler.java
src/test/java/org/ays/common/exception/handler/GlobalExceptionHandlerTest.java

AYS-567 | Refactor method_not_allowed response message to be API_ERROR

---

src/main/java/org/ays/auth/exception/AysUserAlreadyPassiveException.java
src/main/java/org/ays/auth/exception/AysUserNotActiveAuthException.java
src/main/java/org/ays/auth/exception/AysUserNotActiveException.java
src/main/java/org/ays/auth/service/AysUserUpdateService.java
src/main/java/org/ays/auth/service/impl/AysAuthServiceImpl.java
src/main/java/org/ays/auth/service/impl/AysUserPasswordServiceImpl.java
src/main/java/org/ays/auth/service/impl/AysUserUpdateServiceImpl.java
src/test/java/org/ays/auth/controller/AysUserEndToEndTest.java
src/test/java/org/ays/auth/service/impl/AysAuthServiceImplTest.java
src/test/java/org/ays/auth/service/impl/AysUserPasswordServiceImplTest.java
src/test/java/org/ays/auth/service/impl/AysUserUpdateServiceImplTest.java

AYS-660 | Change Error Code and Message for Already Passive Users

---

src/main/java/org/ays/auth/exception/AysUserAlreadyActiveException.java
src/main/java/org/ays/auth/exception/AysUserNotPassiveException.java
src/main/java/org/ays/auth/service/impl/AysUserUpdateServiceImpl.java
src/test/java/org/ays/auth/controller/AysUserEndToEndTest.java
src/test/java/org/ays/auth/service/impl/AysUserUpdateServiceImplTest.java
src/test/java/org/ays/util/AysMockResultMatchersBuilders.java

…ve user
- Necessary documentation has been added or existing documentation has been …

AYS-659 | Refactor error code from 404 to 409 when trying to activate an already active user

---

src/main/java/org/ays/auth/service/impl/AysPermissionServiceImpl.java
src/main/java/org/ays/common/util/AysRandomUtil.java
src/main/java/org/ays/common/util/validation/NameValidator.java
src/test/java/org/ays/auth/model/AysUserBuilder.java

AYS-903 Resolve SonarQube Issues
