afet-yonetim-sistemi/ays-be

src/main/java/com/ays/backend/mapper/UserMapper.java
src/main/java/com/ays/backend/user/controller/UserController.java
src/main/java/com/ays/backend/user/controller/payload/request/UpdateUserRequest.java
src/main/java/com/ays/backend/user/model/entities/BaseEntity.java
src/main/java/com/ays/backend/user/repository/UserRepository.java
src/main/java/com/ays/backend/user/service/UserService.java
src/main/java/com/ays/backend/user/service/dto/UserDTO.java
src/main/java/com/ays/backend/user/service/impl/UserServiceImpl.java
src/test/java/com/ays/backend/user/controller/UserControllerTest.java
src/test/java/com/ays/backend/user/model/entities/UserBuilder.java
src/test/java/com/ays/backend/user/service/UserServiceTest.java
src/test/java/com/ays/backend/user/service/dto/UserDTOBuilder.java

What I have done so far is focused on all these processes shown below.
1 ) Implementation of deleting user softly by the specified ID
2 ) Implementation of updating user by the specified ID

Implementation of Soft Delete User and Update User

---

.gitignore
Dockerfile
README.md
docker-compose.yml

Accelerating the Initial Project Setup Processes and Documentation

---

CONTRIBUTING.md
ISSUE_TEMPLATE.md
LICENSE.md
PULL_REQUEST_TEMPLATE.md
SECURITY.md

This **pull request** performs implementing and researching the **standards** required for the **GitHub Community Standards** of `afet-yönetim-sistemi` backend project.
What I have done so far is shown below
**1 )** Define `CONTRIBUTING.md` 
**2 )** Define `LICENSE.md`
**3 )** Define `SECURITY.md`
**4 )** Define `PULL_REQUEST_TEMPLATE.md` 
**5 )** Define `ISSUE_TEMPLATE.md`

Improvement GitHub community standart

---

README.md
docker-compose.yml
src/main/resources/application-development.yml
src/main/resources/application.yml

Bilgisayarında MySQL default olarak kurulu olabilmesi ihtimali sebebiyle MySQL portunu değiştirmekle uğraşmamak için `3307` portuna aldım ve bir kaç ufak düzeltme yaptım. README.md'deki .env kısmına da bizim kendi kurulumlarımızda yeni yapı sebebiyle ihtiyaç olmuyor.

`docker-compose` and `README.md` Files Have Been Refactored & MySQL Port Has Been Changed as `3307`

---

src/main/java/com/ays/auth/config/SecurityConfiguration.java

As some methods are deprecated in filterChain of SecurityConfiguration class, all these methods are revised
The number of issue is 113
- Feature/issue-number/feature-description: [Feature Description]
- Refactor/issue-number/issue-description: [Issue Description]
- ...
board or milestone. However, if there is no issue, the pull request should be …

Refactor filterChain of SecurityConfiguration

---

src/main/java/com/ays/common/model/entity/BaseEntity.java

Refactor default createdUser and updatedUser value
In the process of registering admin, createdUser and updatedUser values cannot be set as the JWT token cannot be valid. 
Revise the process to determine if the JWT token is valid for registering the admin.
- refactor/116/determine-default-createduser-and-updateduser-value
board (BE Board, In Review column) and milestone to track the progress.
The default project maintainers and team members will be automatically assigned as reviewers for this pull request.

#116 | Refactor default createdUser and updatedUser values

---

src/main/java/com/ays/common/util/validation/PhoneNumber.java
src/main/java/com/ays/common/util/validation/PhoneNumberValidator.java
src/main/java/com/ays/user/model/dto/request/UserSupportStatusUpdateRequest.java
src/main/java/com/ays/user/model/dto/request/UserUpdateRequest.java
src/test/java/com/ays/admin_user/controller/AdminUserAuthControllerTest.java
src/test/java/com/ays/common/util/exception/model/AysErrorBuilder.java
src/test/java/com/ays/user/controller/UserAuthControllerTest.java
src/test/java/com/ays/user/controller/UserControllerTest.java
src/test/java/com/ays/util/AysMockResultMatchersBuilders.java

In some flows, the object types used in the phone number information have changed, so the incoming value is expected to be a number, and length validations have been added. Unit tests have been written for this.
board (BE Board, In Review column) and milestone to track the progress.
The default project maintainers and team members will be automatically assigned as reviewers for this pull request.

Phone Number Validations Has Been Fixed

---

src/main/java/com/ays/auth/config/SecurityConfiguration.java
src/main/resources/application.yml

**Improvments**
- `/actuator/info` and `/actuator/health` Endpoints Have Been Exposed 
- `/actuator/info` Endpoint Has Been Customized for Application

#132 | Enabling Application Information Service with Spring Boot Actuator

---

README.md

read.me kısmı için güncellemeler yapıldı
// Read.me için açıklamalar eklendi bu açıklamar projeyi yeni tanıyonn bir kişinin projeyi anlayabilmesi için oluşturuldu.
#144 
projeye desription ,process süreci eklendi tech için bazı alanlar günncellenip eklendi
board (BE Board, In Review column) and milestone to track the progress.
The default project maintainers and team members will be automatically assigned as reviewers for this pull request.

Improvement README.md file

---

src/main/java/com/ays/assignment/controller/AssignmentController.java
src/main/java/com/ays/assignment/repository/AssignmentRepository.java
src/main/java/com/ays/assignment/service/AssignmentService.java
src/main/java/com/ays/assignment/service/impl/AssignmentServiceImpl.java
src/main/resources/db/changelog/changes/5-ays-dml.xml
src/test/java/com/ays/assignment/controller/AssignmentControllerTest.java
src/test/java/com/ays/assignment/controller/AssignmentSystemTest.java
src/test/java/com/ays/assignment/model/AssignmentBuilder.java
src/test/java/com/ays/assignment/service/impl/AssignmentServiceImplTest.java
src/test/java/com/ays/util/AysTestData.java

- Implement the process of getting Assignment by Id
If this pull request is related to any GitHub issue, please mention it here with the appropriate issue number.
board or milestone. However, if …

#94 | Implement the process of getting Assignment by ID

---

src/main/java/com/ays/assignment/controller/AssignmentController.java
src/main/java/com/ays/assignment/model/dto/request/AssignmentUpdateRequest.java
src/main/java/com/ays/assignment/model/entity/AssignmentEntity.java
src/main/java/com/ays/assignment/model/mapper/AssignmentUpdateRequestToAssignmentEntityMapper.java
src/main/java/com/ays/assignment/service/AssignmentService.java
src/main/java/com/ays/assignment/service/impl/AssignmentServiceImpl.java
src/main/java/com/ays/user/model/entity/UserEntity.java
src/main/java/com/ays/user/service/impl/UserServiceImpl.java
src/test/java/com/ays/assignment/controller/AssignmentControllerTest.java
src/test/java/com/ays/assignment/controller/AssignmentSystemTest.java
src/test/java/com/ays/assignment/model/dto/request/AssignmentUpdateRequestBuilder.java
src/test/java/com/ays/assignment/service/impl/AssignmentServiceImplTest.java
src/test/java/com/ays/user/service/impl/UserServiceImplTest.java

Implemented the `Update Assignment` endpoint
#148 
If this pull request is related to any GitHub issue, please mention it here with the appropriate issue number.
Please check the …

#148 | Implementation of 'Update Assignment' API Endpoint

---

src/main/java/com/ays/common/util/exception/handler/GlobalExceptionHandler.java

I added global exception handler for JSON parsing error.  
#171 
board (BE …

#171 | Added global exception handler for JSON parsing error

---

src/main/java/com/ays/common/util/exception/handler/GlobalExceptionHandler.java
src/test/java/com/ays/common/util/exception/handler/GlobalExceptionHandlerTest.java

- Implement the process of handleHttpRequestMethodNotSupportedException, handleHttpMediaTypeNotSupportedException and handleDataAccessException
- Write other exception handling test method in GlobalExceptionHandlerTest
#182
Please check the following before …

Implement the process of other exception handling method and Write other exception handling test method in GlobalExceptionHandlerTest

---

src/main/java/com/ays/assignment/util/exception/AysAssignmentUserNotReadyException.java

AysAssignmentUserNotReadyException's Exception Type is Changed to AysAlreadyException from AysAuthException
#179 
board or milestone. However, if there is no issue, the pull request should be …

#179 | Change the Exception Type of the AysAssignmentUserNotReadyException

---

src/main/java/com/ays/assignment/model/dto/request/AssignmentSaveRequest.java
src/main/java/com/ays/assignment/model/dto/request/AssignmentSearchRequest.java
src/main/java/com/ays/assignment/model/dto/request/AssignmentUpdateRequest.java
src/main/java/com/ays/location/model/dto/request/UserLocationSaveRequest.java

Added a validation to check if the requested location parameters are in the valid range.
#186  …

#186 | Add Min & Max annotations to the location request fields

---

src/main/java/com/ays/assignment/repository/AssignmentRepository.java
src/main/java/com/ays/assignment/service/impl/AssignmentSearchServiceImpl.java
src/main/java/com/ays/assignment/util/exception/AysAssignmentUserAlreadyAssigned.java
src/test/java/com/ays/assignment/service/impl/AssignmentSearchServiceImplTest.java

Implemented User's Assigment's Existence Check in Assignment Search Flow.
#180 
board or milestone. However, if there is no issue, the pull request should be associated with the appropriate …

#180 | Resolved The User Assignment Existence Bug in Assignment Search Flow

---

src/test/java/com/ays/common/util/exception/handler/GlobalExceptionHandlerTest.java

…ReturnAysError method to GlobalExceptionHandlerTest
It is recognized that there is no test method for HttpMessageNotReadableException to GlobalExceptionHandlerTest. That's why I take an action to tackle with that.
#192
Please check the following before …

#192 | Add HttpMessageNotReadableException test method to GlobalExceptionHandlerTest

---

src/main/java/com/ays/location/service/impl/UserLocationServiceImpl.java
src/main/java/com/ays/location/util/exception/AysUserLocationCannotBeUpdatedException.java

Updated the exception message of the class `AysUserLocationCannotBeUpdatedException`
#189  …

#189 | Update AysUserLocationCannotBeUpdatedException Exception Message

---

src/main/resources/banner.txt

Created a custom banner for the logs
#198 
board (BE Board, In Review column) …

#198 | Add Custom Banner

---

src/main/java/com/ays/admin_user/model/dto/request/AdminUserRegisterRequest.java
src/main/java/com/ays/assignment/model/dto/request/AssignmentSaveRequest.java
src/main/java/com/ays/assignment/model/dto/request/AssignmentUpdateRequest.java
src/main/java/com/ays/common/util/validation/Name.java
src/main/java/com/ays/common/util/validation/NameValidator.java
src/main/java/com/ays/user/model/dto/request/UserSaveRequest.java
src/test/java/com/ays/admin_user/controller/AdminUserAuthControllerTest.java
src/test/java/com/ays/admin_user/model/dto/request/AdminUserRegisterRequestBuilder.java
src/test/java/com/ays/assignment/controller/AssignmentControllerTest.java
src/test/java/com/ays/assignment/model/dto/request/AssignmentUpdateRequestBuilder.java
src/test/java/com/ays/user/controller/UserControllerTest.java
src/test/java/com/ays/user/model/dto/request/UserSaveRequestBuilder.java

Added a custom validation for the request classes that contain first & last name fields
#195  …

#195 | Implement Custom Validation for First and Last Name Fields

---

src/main/java/com/ays/common/util/validation/PhoneNumberValidator.java

I added a null check in `PhoneNumberValidator` to return true if any attributes are null. This allows the Spring Validator to trigger an exception at the `NotNull` annotation.
#207 
board or …

#207 | Add a Null Check to `PhoneNumberValidator`

---

README.md
pom.xml

> Java Version Hasn't Been Upgraded to 21 Because Application Container Not Compatibility Yet Running On Java 21

#213 | Spring and Other Dependencies Versions Have Been Upgraded to Latest

---

src/main/java/com/ays/common/model/AysPaging.java

If this pull request is related to any GitHub issue, please mention it here with the appropriate issue number.
board …

#216 | Add a Null Check to `getPage` method in `AysPaging`

---

src/main/java/com/ays/user/model/dto/request/UserSaveRequest.java

Changed the `@NotNull` annotations to `@NotBlank` annotation in `UserSaveRequest` class.
#217  …

#217 | Change `NotNull` annotations to `NotBlank` in `UserSaveRequest` Class

---

src/main/java/com/ays/common/util/validation/NameValidator.java

Restricted names from starting and/or ending with white-spaces.
#210 
board …

#210 | Restrict Names from Starting/Ending with Spaces

---

pom.xml
src/main/java/com/ays/common/util/validation/PhoneNumberValidator.java
src/test/java/com/ays/admin_user/controller/AdminUserAuthControllerTest.java
src/test/java/com/ays/admin_user/controller/AdminUserAuthSystemTest.java
src/test/java/com/ays/common/model/AysPhoneNumberBuilder.java
src/test/java/com/ays/user/controller/UserControllerTest.java

Applied the `E.164` `International Phone Number Standards` on the project.
#208 #212 
board or milestone. However, if there is no issue, the pull request should be associated with the appropriate …

#208 - #212 | Apply International Phone Number Standards

---

src/main/java/com/ays/assignment/controller/AssignmentController.java
src/main/java/com/ays/assignment/model/dto/response/AssignmentUserResponse.java
src/main/java/com/ays/assignment/model/entity/AssignmentEntity.java
src/main/java/com/ays/assignment/model/mapper/AssignmentToAssignmentUserResponseMapper.java
src/main/java/com/ays/assignment/service/AssignmentService.java
src/main/java/com/ays/assignment/service/impl/AssignmentServiceImpl.java
src/main/java/com/ays/assignment/util/exception/AysAssignmentNotExistByUserIdException.java
src/test/java/com/ays/assignment/controller/AssignmentControllerTest.java
src/test/java/com/ays/assignment/controller/AssignmentSystemTest.java
src/test/java/com/ays/assignment/service/impl/AssignmentServiceImplTest.java

I added `GET /api/v1/assignment` endpoint that provides users can get their assignment.
#232  …

#232 | Added Endpoint That Provides Users Can Get Their Assignments

---

src/main/java/com/ays/assignment/controller/AssignmentController.java
src/main/java/com/ays/assignment/model/dto/response/AssignmentSummaryResponse.java
src/main/java/com/ays/assignment/model/mapper/AssignmentToAssignmentSummaryResponseMapper.java
src/main/java/com/ays/assignment/repository/AssignmentRepository.java
src/main/java/com/ays/assignment/service/AssignmentService.java
src/main/java/com/ays/assignment/service/impl/AssignmentServiceImpl.java
src/main/java/com/ays/assignment/util/exception/AysAssignmentNotExistByUserIdAndStatusException.java
src/test/java/com/ays/assignment/controller/AssignmentControllerTest.java
src/test/java/com/ays/assignment/controller/AssignmentSystemTest.java
src/test/java/com/ays/assignment/service/impl/AssignmentServiceImplTest.java

Added `GET /assignment/summary` endpoint.
#225 
board (BE Board, In Review …

#225 | Add Assignment Summary Endpoint

---

src/main/java/com/ays/admin_user/controller/AdminUserRegisterApplicationController.java
src/main/java/com/ays/admin_user/model/AdminUserRegisterApplication.java
src/main/java/com/ays/admin_user/model/mapper/AdminUserRegisterApplicationEntityToAdminUserRegisterApplication.java
src/main/java/com/ays/admin_user/service/AdminUserRegisterApplicationService.java
src/main/java/com/ays/admin_user/service/impl/AdminUserRegisterApplicationServiceImpl.java
src/test/java/com/ays/admin_user/controller/AdminUserRegisterApplicationControllerTest.java
src/test/java/com/ays/admin_user/controller/AdminUserRegisterApplicationSystemTest.java
src/test/java/com/ays/admin_user/service/impl/AdminUserRegisterApplicationServiceImplTest.java

Created the main classes for the admin register application flow. The main reason for this pull request to be created is to avoid possible conflicts while developing the register application flow in parallel with other developers.
There's no direct related issue with this pull request. 
If there's any additional information or context that the reviewers should …

Create the Main Structure for Admin Register Application Flow

---

src/main/java/com/ays/user/model/dto/response/UsersResponse.java

Revise UsersResponse for Users Detail Endpoint
#258 
If this pull request is related to any GitHub issue, please mention it here with the appropriate issue number.
board or milestone. However, if …

#258 | Revise UsersResponse for Users Detail Endpoint

---

src/main/java/com/ays/admin_user/controller/AdminUserRegisterApplicationController.java
src/main/java/com/ays/admin_user/model/dto/response/AdminUserRegisterApplicationSummaryResponse.java
src/main/java/com/ays/admin_user/model/mapper/AdminUserRegisterApplicationToAdminUserRegisterApplicationSummaryResponseMapper.java
src/main/java/com/ays/admin_user/service/AdminUserRegisterApplicationService.java
src/main/java/com/ays/admin_user/service/impl/AdminUserRegisterApplicationServiceImpl.java
src/main/java/com/ays/admin_user/util/exception/AysAdminUserRegisterApplicationNotExistByIdAndStatusException.java
src/main/java/com/ays/auth/config/SecurityConfiguration.java
src/test/java/com/ays/admin_user/controller/AdminUserRegisterApplicationControllerTest.java
src/test/java/com/ays/admin_user/controller/AdminUserRegisterApplicationSystemTest.java
src/test/java/com/ays/admin_user/service/impl/AdminUserRegisterApplicationServiceImplTest.java
src/test/java/com/ays/util/AysMockMvcRequestBuilders.java

I have implemented the admin registration application summary endpoint.
#230  …

#230 | Implement Admin Registration Application Summary Endpoint

---

src/main/java/com/ays/admin_user/controller/AdminUserRegisterApplicationController.java
src/main/java/com/ays/admin_user/model/dto/request/AdminUserRegisterApplicationCreateRequest.java
src/main/java/com/ays/admin_user/model/dto/response/AdminUserRegisterApplicationCreateResponse.java
src/main/java/com/ays/admin_user/model/entity/AdminUserRegisterApplicationEntity.java
src/main/java/com/ays/admin_user/model/mapper/AdminUserRegisterApplicationCreateRequestToAdminUserRegisterApplicationEntityMapper.java
src/main/java/com/ays/admin_user/model/mapper/AdminUserRegisterApplicationToAdminUserRegisterApplicationCreateResponseMapper.java
src/main/java/com/ays/admin_user/service/AdminUserRegisterApplicationService.java
src/main/java/com/ays/admin_user/service/impl/AdminUserRegisterApplicationServiceImpl.java
src/main/java/com/ays/common/util/AysRandomUtil.java
src/main/java/com/ays/institution/repository/InstitutionRepository.java
src/test/java/com/ays/admin_user/controller/AdminUserRegisterApplicationControllerTest.java
src/test/java/com/ays/admin_user/controller/AdminUserRegisterApplicationSystemTest.java
src/test/java/com/ays/admin_user/model/AdminUserRegisterApplicationBuilder.java
src/test/java/com/ays/admin_user/model/dto/request/AdminUserRegisterApplicationCreateRequestBuilder.java
src/test/java/com/ays/admin_user/model/entity/AdminUserRegisterApplicationEntityBuilder.java
src/test/java/com/ays/admin_user/service/impl/AdminUserRegisterApplicationServiceImplTest.java
src/test/java/com/ays/common/util/AysRandomTestUtil.java

I added an endpoint to create an admin register application endpoint.
#231  …

#231 | Implement Admin Registration Application Create Endpoint

---

src/main/java/com/ays/admin_user/model/dto/response/AdminUserRegisterApplicationSummaryResponse.java

I have removed the institution id information from the specified endpoint.
https://afetyonetimsistemi.atlassian.net/browse/AYS-80
board or milestone. However, if there is no issue, the pull …

AYS - 80 | Remove Institution Id from Admin User Registration Summary Endpoint

---

src/main/java/com/ays/admin_user/controller/AdminUserRegisterApplicationController.java
src/main/java/com/ays/admin_user/model/entity/AdminUserEntity.java
src/main/java/com/ays/admin_user/model/entity/AdminUserRegisterApplicationEntity.java
src/main/java/com/ays/admin_user/service/AdminUserRegisterApplicationService.java
src/main/java/com/ays/admin_user/service/impl/AdminUserRegisterApplicationServiceImpl.java
src/test/java/com/ays/admin_user/controller/AdminUserRegisterApplicationControllerTest.java
src/test/java/com/ays/admin_user/controller/AdminUserRegisterApplicationSystemTest.java
src/test/java/com/ays/admin_user/model/AdminUserBuilder.java
src/test/java/com/ays/admin_user/model/AdminUserRegisterApplicationBuilder.java
src/test/java/com/ays/admin_user/model/entity/AdminUserEntityBuilder.java
src/test/java/com/ays/admin_user/service/impl/AdminUserRegisterApplicationServiceImplTest.java

AYS-26 | Added approve endpoint for admin user register application

---

src/main/java/com/ays/admin_user/controller/AdminUserRegisterApplicationController.java
src/main/java/com/ays/admin_user/model/dto/request/AdminUserRegisterApplicationRejectRequest.java
src/main/java/com/ays/admin_user/model/entity/AdminUserEntity.java
src/main/java/com/ays/admin_user/model/entity/AdminUserRegisterApplicationEntity.java
src/main/java/com/ays/admin_user/service/AdminUserRegisterApplicationService.java
src/main/java/com/ays/admin_user/service/impl/AdminUserRegisterApplicationServiceImpl.java
src/test/java/com/ays/admin_user/controller/AdminUserRegisterApplicationControllerTest.java
src/test/java/com/ays/admin_user/controller/AdminUserRegisterApplicationSystemTest.java
src/test/java/com/ays/admin_user/model/AdminUserBuilder.java
src/test/java/com/ays/admin_user/model/dto/request/AdminUserRegisterApplicationRejectRequestBuilder.java
src/test/java/com/ays/admin_user/model/entity/AdminUserEntityBuilder.java
src/test/java/com/ays/admin_user/service/impl/AdminUserRegisterApplicationServiceImplTest.java

AYS-25 | Added reject admin register application endpoint

---

pom.xml
src/main/java/com/ays/admin_user/service/impl/AdminUserAuthServiceImpl.java
src/main/java/com/ays/auth/filter/AysBearerTokenAuthenticationFilter.java
src/main/java/com/ays/auth/service/AysTokenService.java
src/main/java/com/ays/auth/service/impl/AysTokenServiceImpl.java
src/main/java/com/ays/user/service/impl/UserAuthServiceImpl.java
src/test/java/com/ays/AbstractRestControllerTest.java
src/test/java/com/ays/AbstractSystemTest.java
src/test/java/com/ays/admin_user/service/impl/AdminUserAuthServiceImplTest.java
src/test/java/com/ays/auth/service/impl/AysTokenServiceImplTest.java
src/test/java/com/ays/user/service/impl/UserAuthServiceImplTest.java

AYS-101 | Version of All Dependencies Have Been Upgraded to Latest

---

src/main/java/com/ays/admin_user/model/mapper/AdminUserEntityToAdminUserMapper.java
src/main/java/com/ays/admin_user/model/mapper/AdminUserRegisterApplicationEntityToAdminUserRegisterApplicationMapper.java
src/main/java/com/ays/admin_user/model/mapper/AdminUserRegisterApplicationToAdminUserRegisterApplicationResponseMapper.java
src/main/java/com/ays/user/model/mapper/UserEntityToUserMapper.java
src/test/java/com/ays/admin_user/controller/AdminUserRegisterApplicationSystemTest.java
src/test/java/com/ays/util/AysMockResultMatchersBuilders.java

AYS-2 | Admin User Phone Number Mapping Has Been Fixed in Mapping Application Entity to Application Domain Model

---

src/main/java/com/ays/admin_user/controller/AdminUserAuthController.java
src/main/java/com/ays/admin_user/controller/AdminUserRegisterApplicationController.java
src/main/java/com/ays/admin_user/model/dto/request/AdminUserRegisterApplicationCompleteRequest.java
src/main/java/com/ays/admin_user/model/mapper/AdminUserRegisterRequestToAdminUserEntityMapper.java
src/main/java/com/ays/admin_user/service/AdminUserRegisterService.java
src/main/java/com/ays/admin_user/service/impl/AdminUserRegisterServiceImpl.java
src/main/java/com/ays/auth/config/SecurityConfiguration.java
src/test/java/com/ays/admin_user/controller/AdminUserAuthControllerTest.java
src/test/java/com/ays/admin_user/controller/AdminUserAuthSystemTest.java
src/test/java/com/ays/admin_user/controller/AdminUserRegisterApplicationControllerTest.java
src/test/java/com/ays/admin_user/controller/AdminUserRegisterApplicationSystemTest.java
src/test/java/com/ays/admin_user/model/dto/request/AdminUserRegisterApplicationCompleteRequestBuilder.java
src/test/java/com/ays/admin_user/model/dto/request/AdminUserRegisterRequestBuilder.java
src/test/java/com/ays/admin_user/service/impl/AdminUserRegisterServiceImplTest.java

I have revised the admin user register endpoint to an endpoint where admin users complete their register applications.
AYS - 24
board or milestone. However, if there is no issue, the pull request …

AYS-24 | Implements the Complete Admin User Register Application Endpoint

---

src/main/java/com/ays/user/model/dto/response/UsersResponse.java
src/test/java/com/ays/user/controller/UserControllerTest.java
src/test/java/com/ays/user/controller/UserSystemTest.java

AYS-127 | `createdAt` Field Has Been Added to UsersResponse Class

---

src/main/java/com/ays/admin_user/service/impl/AdminUserAuthServiceImpl.java
src/main/java/com/ays/user/service/impl/UserAuthServiceImpl.java
src/test/java/com/ays/admin_user/service/impl/AdminUserAuthServiceImplTest.java
src/test/java/com/ays/user/service/impl/UserAuthServiceImplTest.java

AYS-130 Invalidated Refresh Token Flow Fix

---

README.md

AYS-129 | Postman Collection and Environments Links Have Been Changed in `README.md` File

---

src/test/java/com/ays/AbstractRestControllerTest.java
src/test/java/com/ays/AbstractSystemTest.java
src/test/java/com/ays/AysMockMvc.java
src/test/java/com/ays/admin_user/controller/AdminUserAuthControllerTest.java
src/test/java/com/ays/admin_user/controller/AdminUserAuthSystemTest.java
src/test/java/com/ays/admin_user/controller/AdminUserControllerTest.java
src/test/java/com/ays/admin_user/controller/AdminUserRegisterApplicationControllerTest.java
src/test/java/com/ays/admin_user/controller/AdminUserRegisterApplicationSystemTest.java
src/test/java/com/ays/admin_user/controller/AdminUserSystemTest.java
src/test/java/com/ays/assignment/controller/AssignmentControllerTest.java
src/test/java/com/ays/assignment/controller/AssignmentSystemTest.java
src/test/java/com/ays/common/model/dto/response/AysResponseBuilder.java
src/test/java/com/ays/institution/controller/InstitutionControllerTest.java
src/test/java/com/ays/institution/controller/InstitutionSystemTest.java
src/test/java/com/ays/location/controller/UserLocationControllerTest.java
src/test/java/com/ays/location/controller/UserLocationSystemTest.java
src/test/java/com/ays/user/controller/UserAuthControllerTest.java
src/test/java/com/ays/user/controller/UserAuthSystemTest.java
src/test/java/com/ays/user/controller/UserControllerTest.java
src/test/java/com/ays/user/controller/UserSelfControllerTest.java
src/test/java/com/ays/user/controller/UserSelfSystemTest.java
src/test/java/com/ays/user/controller/UserSystemTest.java
src/test/java/com/ays/user/service/impl/UserSelfServiceImplTest.java
src/test/java/com/ays/util/AysMockMvc.java

AYS-131 | All Integration and End-to-End Tests Have Been Refactored with AysMockMvc Infrastructure

---

src/main/java/org/ays/admin_user/model/dto/request/AdminUserRegisterApplicationCompleteRequest.java
src/main/java/org/ays/common/util/validation/Email.java
src/main/java/org/ays/common/util/validation/EmailValidator.java
src/test/java/org/ays/admin_user/controller/AdminUserRegisterApplicationControllerTest.java

AYS-160 | Registering with Invalid Domain Extension Email

---

src/main/java/org/ays/admin_user/model/dto/request/AdminUserRegisterApplicationCreateRequest.java
src/main/java/org/ays/common/util/validation/NoSpecialCharacters.java
src/main/java/org/ays/common/util/validation/SpecialCharacterValidator.java
src/test/java/org/ays/admin_user/controller/AdminUserRegisterApplicationControllerTest.java

AYS-121 | Added Validation for Character Restriction And Special Character Control To The Reason Field

---

Dockerfile
docker-compose.yml
pom.xml

AYS-195 | All Dependencies and Docker Files Have Been Upgraded and Vulnerabilities Have Been Fixed

---

src/main/java/org/ays/common/util/validation/SpecialCharacterValidator.java
src/test/java/org/ays/admin_user/controller/AdminUserRegisterApplicationControllerTest.java

AYS-121 | The Reason Field Is A Number Checked

---

src/main/resources/db/changelog/changes/3-ays-ddl.xml

AYS-209 | `AYS_EMERGENCY_EVACUATION_APPLICATION` Table Has Been Created

---

src/main/resources/db/changelog/changes/4-ays-ddl.xml
src/main/resources/db/changelog/changes/5-ays-dml.xml

AYS-225 | Tables and Initial Data Have Been Created for User/Role/Permission Management

---

pom.xml
template-settings.xml

AYS-257 | All Dependencies, Spring Version Have Been Upgraded and Vulnerabilities Have Been Fixed

---

src/main/java/org/ays/common/util/validation/SpecialCharacterValidator.java
src/main/java/org/ays/user/model/dto/request/AdminRegistrationApplicationCreateRequest.java
src/test/java/org/ays/user/controller/AdminRegistrationApplicationControllerTest.java

AYS-121 | Special Character Annotation Added To Reason Field  

---

src/main/java/org/ays/auth/model/dto/request/AysLoginRequestV2.java
src/main/java/org/ays/common/model/entity/BaseEntity.java
src/main/java/org/ays/institution/controller/InstitutionController.java
src/main/java/org/ays/user/controller/AdminRegistrationApplicationController.java
src/test/java/org/ays/user/controller/AdminRegistrationApplicationControllerTest.java
src/test/java/org/ays/user/controller/AdminRegistrationApplicationSystemTest.java
src/test/java/org/ays/user/controller/UserAuthControllerV2Test.java

AYS-199 | `@Email` Annotation Has Been Added to `AysLoginRequestV2.emailAddress` Field

---

src/main/java/org/ays/user/controller/UserAuthControllerV2.java
src/test/java/org/ays/user/controller/UserAuthControllerV2Test.java
src/test/java/org/ays/user/controller/UserAuthSystemV2Test.java

AYS-199 | ` @PreAuthorize` Annotation Has Been Deleted from `/token/invalidate` Endpoint

---

src/main/java/org/ays/auth/model/AysIdentity.java
src/main/java/org/ays/auth/service/impl/AysTokenServiceImpl.java
src/main/java/org/ays/user/controller/PermissionController.java
src/main/java/org/ays/user/model/Permission.java
src/main/java/org/ays/user/model/dto/response/PermissionsResponse.java
src/main/java/org/ays/user/model/entity/PermissionEntity.java
src/main/java/org/ays/user/model/mapper/PermissionEntityToPermissionMapper.java
src/main/java/org/ays/user/model/mapper/PermissionToPermissionsResponseMapper.java
src/main/java/org/ays/user/service/PermissionService.java
src/main/java/org/ays/user/service/impl/PermissionServiceImpl.java
src/main/resources/db/changelog/changes/4-ays-ddl.xml
src/test/java/org/ays/AbstractRestControllerTest.java
src/test/java/org/ays/AbstractSystemTest.java
src/test/java/org/ays/user/controller/PermissionControllerTest.java
src/test/java/org/ays/user/controller/PermissionSystemTest.java
src/test/java/org/ays/user/model/PermissionBuilder.java
src/test/java/org/ays/user/model/dto/response/PermissionsResponseBuilder.java
src/test/java/org/ays/user/service/impl/PermissionServiceImplTest.java
src/test/java/org/ays/util/AysValidTestData.java

AYS-236 | Permission List Flow Has Been Created End to End

---

src/main/java/org/ays/common/util/exception/handler/GlobalExceptionHandler.java
src/test/java/org/ays/common/util/exception/handler/GlobalExceptionHandlerTest.java

AYS-254 | Add handler for NoResourceFoundException

---

src/main/java/org/ays/common/util/validation/SpecialCharacterValidator.java
src/test/java/org/ays/user/controller/AdminRegistrationApplicationControllerTest.java

AYS-121 | Added valid characters to regex 

---

src/main/java/org/ays/common/util/exception/AysAlreadyException.java
src/main/java/org/ays/common/util/exception/AysInvalidStatusException.java
src/main/java/org/ays/common/util/exception/handler/GlobalExceptionHandler.java
src/main/java/org/ays/common/util/exception/model/AysErrorResponse.java
src/main/java/org/ays/user/model/entity/AdminRegistrationApplicationEntity.java
src/main/java/org/ays/user/service/impl/AdminRegistrationApplicationServiceImpl.java
src/main/java/org/ays/user/util/exception/AysAdminRegistrationApplicationAlreadyApprovedException.java
src/main/java/org/ays/user/util/exception/AysAdminRegistrationApplicationAlreadyRejectedException.java
src/main/java/org/ays/user/util/exception/AysAdminRegistrationApplicationInCompleteException.java
src/test/java/org/ays/common/util/exception/handler/GlobalExceptionHandlerTest.java
src/test/java/org/ays/common/util/exception/model/AysErrorBuilder.java
src/test/java/org/ays/user/controller/AdminRegistrationApplicationSystemTest.java
src/test/java/org/ays/user/service/impl/AdminRegistrationApplicationServiceImplTest.java

AYS-196: Add checks on reject endpoint so that only valid entities can be rejected

---

src/main/java/org/ays/common/model/dto/request/AysPhoneNumberRequest.java
src/main/java/org/ays/emergency_application/model/dto/request/EmergencyEvacuationApplicationRequest.java
src/test/java/org/ays/emergency_application/controller/EmergencyEvacuationApplicationControllerTest.java
src/test/java/org/ays/emergency_application/controller/EmergencyEvacuationApplicationSystemTest.java
src/test/java/org/ays/emergency_application/model/dto/request/EmergencyEvacuationRequestBuilder.java

AYS-221 | Validations of Emergency Evacuation Application Flow Have Been Fixed

---

src/main/java/org/ays/common/util/exception/handler/GlobalExceptionHandler.java
src/main/java/org/ays/common/util/exception/model/AysErrorResponse.java
src/test/java/org/ays/common/util/exception/handler/GlobalExceptionHandlerTest.java

AYS-261 Enum Validation Added in GlobalExceptionHandler.handleJsonParseErrors

---

src/main/java/org/ays/common/model/request/AysPhoneNumberRequest.java
src/main/java/org/ays/common/util/validation/NameValidator.java
src/main/java/org/ays/emergency_application/model/request/EmergencyEvacuationApplicationRequest.java
src/test/java/org/ays/emergency_application/controller/EmergencyEvacuationApplicationControllerTest.java

AYS-221 | Validations of EmergencyEvacuationApplicationRequest Have Been Fixed

---

src/main/java/org/ays/common/model/response/AysErrorResponse.java

AYS-261 | The SubErrors handling the InvalidFormatException were fixed

---

src/main/java/org/ays/emergency_application/controller/EmergencyEvacuationApplicationController.java
src/test/java/org/ays/emergency_application/controller/EmergencyEvacuationApplicationControllerTest.java

AYS-286 | Invalid Id Response Has Been Fixed

---

src/main/java/org/ays/auth/controller/AysRoleController.java
src/main/java/org/ays/auth/model/entity/AysRoleEntity.java
src/main/java/org/ays/auth/model/request/AysRoleCreateRequest.java
src/main/java/org/ays/auth/model/request/AysRoleUpdateRequest.java
src/main/java/org/ays/auth/service/AysRoleUpdateService.java
src/main/java/org/ays/auth/service/impl/AysRoleCreateServiceImpl.java
src/main/java/org/ays/auth/service/impl/AysRoleUpdateServiceImpl.java
src/main/java/org/ays/auth/util/exception/AysRoleNotExistByIdException.java
src/test/java/org/ays/auth/controller/AdminRegistrationApplicationControllerTest.java
src/test/java/org/ays/auth/controller/AysRoleControllerTest.java
src/test/java/org/ays/auth/controller/AysRoleEndToEndTest.java
src/test/java/org/ays/auth/model/request/AysRoleUpdateRequestBuilder.java
src/test/java/org/ays/auth/service/impl/AysRoleCreateServiceImplTest.java
src/test/java/org/ays/auth/service/impl/AysRoleUpdateServiceImplTest.java
src/test/java/org/ays/util/AysValidTestData.java

AYS-241 | Role Update Flow Has Been Created

---

src/main/java/org/ays/auth/controller/AysRoleController.java
src/main/java/org/ays/auth/port/AysRoleReadPort.java
src/main/java/org/ays/auth/port/impl/AysRoleAdapter.java
src/main/java/org/ays/auth/repository/AysRoleRepository.java
src/main/java/org/ays/auth/service/AysRoleUpdateService.java
src/main/java/org/ays/auth/service/impl/AysRoleUpdateServiceImpl.java
src/main/java/org/ays/auth/util/exception/AysRoleAlreadyDeletedException.java
src/main/java/org/ays/auth/util/exception/AysRoleAssignedToUserException.java
src/test/java/org/ays/auth/controller/AysRoleControllerTest.java
src/test/java/org/ays/auth/controller/AysRoleEndToEndTest.java
src/test/java/org/ays/auth/service/impl/AysRoleUpdateServiceImplTest.java

AYS-244 | Role Delete Endpoint Has Been Created 

---

src/main/java/org/ays/auth/controller/AysRoleController.java
src/main/java/org/ays/auth/model/AysRole.java
src/main/java/org/ays/auth/service/AysRoleUpdateService.java
src/main/java/org/ays/auth/service/impl/AysRoleUpdateServiceImpl.java
src/main/java/org/ays/auth/util/exception/AysInvalidRoleStatusException.java
src/test/java/org/ays/auth/controller/AysRoleControllerTest.java
src/test/java/org/ays/auth/controller/AysRoleEndToEndTest.java
src/test/java/org/ays/auth/service/impl/AysRoleUpdateServiceImplTest.java
src/test/java/org/ays/util/AysMockMvcRequestBuilders.java

AYS-242 | Role Activation Flow Has Been Created

---

PULL_REQUEST_TEMPLATE.md
src/main/java/org/ays/auth/controller/AysRoleController.java
src/main/java/org/ays/auth/model/AysRoleFilter.java
src/main/java/org/ays/auth/model/AysUserFilter.java
src/test/java/org/ays/auth/controller/AysRoleEndToEndTest.java
src/test/java/org/ays/auth/controller/AysUserEndToEndTest.java
src/test/java/org/ays/auth/model/AysInvalidTokenBuilder.java
src/test/java/org/ays/auth/model/AysUserBuilder.java
src/test/java/org/ays/auth/scheduler/InvalidTokenDeletionSchedulerEndToEndTest.java
src/test/java/org/ays/common/model/TestDataBuilder.java

AYS-316 | Search with Like Conditions Have Been Fixed in User and Role List Flows and `TestDataBuilder` Class Has Been Refactored

---

src/main/java/org/ays/auth/controller/AysAuthController.java
src/main/java/org/ays/auth/model/AysUser.java
src/main/java/org/ays/auth/model/entity/AysUserEntity.java
src/main/java/org/ays/auth/model/enums/AysConfigurationParameter.java
src/main/java/org/ays/auth/model/mapper/AysTokenToResponseMapper.java
src/main/java/org/ays/auth/model/request/AysForgotPasswordRequest.java
src/main/java/org/ays/auth/port/impl/AysUserAdapter.java
src/main/java/org/ays/auth/service/AysUserPasswordService.java
src/main/java/org/ays/auth/service/impl/AysUserPasswordServiceImpl.java
src/main/java/org/ays/common/model/AysMail.java
src/main/java/org/ays/common/model/enums/AysMailTemplate.java
src/main/java/org/ays/common/service/impl/AysMailServiceImpl.java
src/main/resources/db/changelog/changes/1-ays-ddl.xml
src/main/resources/db/changelog/changes/2-ays-dml.xml
src/main/resources/mail/template/create-password.html
src/test/java/org/ays/auth/controller/AysAuthControllerTest.java
src/test/java/org/ays/auth/controller/AysAuthEndToEndTest.java
src/test/java/org/ays/auth/model/request/AysForgotPasswordRequestBuilder.java
src/test/java/org/ays/auth/service/impl/AdminRegistrationCompleteServiceImplTest.java
src/test/java/org/ays/auth/service/impl/AysUserPasswordServiceImplTest.java
src/test/java/org/ays/common/model/AysMailBuilder.java
src/test/java/org/ays/common/service/impl/AysMailServiceImplTest.java

AYS-318 | Forgot Password Flow Has Been Created

---

src/main/java/org/ays/auth/model/request/AysRoleUpdateRequest.java
src/main/java/org/ays/auth/service/impl/AysRoleUpdateServiceImpl.java
src/test/java/org/ays/auth/controller/AysRoleControllerTest.java
src/test/java/org/ays/auth/controller/AysRoleEndToEndTest.java
src/test/java/org/ays/auth/model/AysRoleBuilder.java
src/test/java/org/ays/auth/service/impl/AysRoleUpdateServiceImplTest.java

AYS-241 | Validations of `AysRoleUpdateRequest` Have Been Fixed

---

src/main/java/org/ays/auth/model/request/AysRoleCreateRequest.java
src/test/java/org/ays/auth/controller/AysRoleControllerTest.java

AYS-340 | Role Creation Service Validation Errors Have Been Resolved

---

src/main/java/org/ays/auth/model/AysUserFilter.java
src/main/java/org/ays/auth/model/request/AdminRegistrationApplicationCompleteRequest.java
src/main/java/org/ays/auth/model/request/AysForgotPasswordRequest.java
src/main/java/org/ays/auth/model/request/AysLoginRequest.java
src/main/java/org/ays/auth/model/request/AysUserCreateRequest.java
src/main/java/org/ays/auth/model/request/AysUserUpdateRequest.java
src/main/java/org/ays/common/util/validation/EmailAddress.java
src/main/java/org/ays/common/util/validation/EmailAddressValidator.java
src/test/java/org/ays/auth/controller/AysUserEndToEndTest.java
src/test/java/org/ays/auth/model/request/AysUserListRequestBuilder.java

AYS-357 | `emailAddress` Field Has Been Added to `AysUserFilter`

---

src/main/java/org/ays/emergency_application/model/EmergencyEvacuationApplication.java
src/main/java/org/ays/emergency_application/model/filter/EmergencyEvacuationApplicationFilter.java
src/main/java/org/ays/emergency_application/service/impl/EmergencyEvacuationApplicationServiceImpl.java
src/test/java/org/ays/emergency_application/controller/EmergencyEvacuationApplicationEndToEndTest.java
src/test/java/org/ays/emergency_application/model/request/EmergencyEvacuationApplicationListRequestBuilder.java
src/test/java/org/ays/emergency_application/service/impl/EmergencyEvacuationApplicationServiceImplTest.java
src/test/java/org/ays/util/AysMockResultMatchersBuilders.java

AYS-335 | All Emergency Evacuation Application Flows Have Been Refactored for Institution Ownerships

---

src/main/java/org/ays/auth/service/impl/AysRoleUpdateServiceImpl.java
src/test/java/org/ays/auth/service/impl/AysRoleUpdateServiceImplTest.java

AYS-345 | Unable to Delete Roles Not Associated with Institutions

---

src/main/java/org/ays/auth/model/AysUserFilter.java
src/test/java/org/ays/auth/controller/AysUserControllerTest.java

AYS-359 | Name and Surname Size Were Updated in in The User Listing Service

---

src/main/java/org/ays/auth/model/AysUser.java
src/main/java/org/ays/auth/model/entity/AysUserEntity.java
src/main/java/org/ays/auth/service/AysUserPasswordService.java
src/main/java/org/ays/auth/service/impl/AysUserPasswordServiceImpl.java
src/main/resources/db/changelog/changes/1-ays-ddl.xml
src/test/java/org/ays/auth/controller/AysAuthEndToEndTest.java
src/test/java/org/ays/auth/model/AysUserBuilder.java
src/test/java/org/ays/auth/service/impl/AysUserPasswordServiceImplTest.java

AYS-363 | User Password Service Has Been Refactored with New Password Flows

---

src/main/java/org/ays/auth/controller/AysUserController.java
src/main/java/org/ays/auth/service/AysUserUpdateService.java
src/main/java/org/ays/auth/service/impl/AysUserUpdateServiceImpl.java
src/test/java/org/ays/auth/controller/AysRoleEndToEndTest.java
src/test/java/org/ays/auth/controller/AysUserControllerTest.java
src/test/java/org/ays/auth/controller/AysUserEndToEndTest.java
src/test/java/org/ays/auth/service/impl/AysUserUpdateServiceImplTest.java

AYS-74 | User Delete Endpoint Has Been Created 

---

src/main/java/org/ays/auth/controller/AysAuthController.java
src/main/java/org/ays/auth/model/request/AysPasswordCreateRequest.java
src/main/java/org/ays/auth/model/request/AysPasswordForgotRequest.java
src/main/java/org/ays/auth/service/AysUserPasswordService.java
src/main/java/org/ays/auth/service/impl/AysUserPasswordServiceImpl.java
src/test/java/org/ays/auth/controller/AysAuthControllerTest.java
src/test/java/org/ays/auth/controller/AysAuthEndToEndTest.java
src/test/java/org/ays/auth/model/AysUserBuilder.java
src/test/java/org/ays/auth/model/request/AysForgotPasswordRequestBuilder.java
src/test/java/org/ays/auth/model/request/AysPasswordCreateRequestBuilder.java
src/test/java/org/ays/auth/service/impl/AysUserPasswordServiceImplTest.java

AYS-328 | Create Password Flow Has Been Created

---

src/main/java/org/ays/auth/service/impl/AysUserPasswordServiceImpl.java
src/test/java/org/ays/auth/controller/AysAuthEndToEndTest.java
src/test/java/org/ays/auth/service/impl/AysUserPasswordServiceImplTest.java

AYS-328 | Forgot Password Flow Has Been Fixed

---

src/main/java/org/ays/auth/model/response/AdminRegistrationApplicationsResponse.java
src/test/java/org/ays/auth/controller/AdminRegistrationApplicationEndToEndTest.java

AYS-303 | delete "user" variable in AdminRegistrationApplicationsResponse model

---

src/main/java/org/ays/auth/service/impl/AysRoleUpdateServiceImpl.java
src/test/java/org/ays/auth/controller/AysRoleControllerTest.java
src/test/java/org/ays/auth/service/impl/AysRoleUpdateServiceImplTest.java

AYS-243 | Prevent Role Passivation if Assigned to a User

---

src/main/java/org/ays/auth/model/request/AdminRegistrationApplicationCompleteRequest.java
src/main/java/org/ays/auth/model/request/AysLoginRequest.java
src/main/java/org/ays/auth/model/request/AysPasswordCreateRequest.java
src/main/java/org/ays/common/model/response/AysErrorResponse.java
src/main/java/org/ays/common/util/validation/NoSpecialCharacterValidator.java
src/main/java/org/ays/common/util/validation/NoSpecialCharacters.java
src/main/java/org/ays/common/util/validation/Password.java
src/main/java/org/ays/common/util/validation/PasswordValidator.java
src/test/java/org/ays/auth/controller/AdminRegistrationApplicationControllerTest.java
src/test/java/org/ays/auth/controller/AdminRegistrationApplicationEndToEndTest.java
src/test/java/org/ays/auth/controller/AysAuthControllerTest.java
src/test/java/org/ays/auth/controller/AysPermissionControllerTest.java
src/test/java/org/ays/auth/controller/AysRoleControllerTest.java
src/test/java/org/ays/auth/controller/AysUserControllerTest.java
src/test/java/org/ays/auth/model/request/AdminRegistrationApplicationCompleteRequestBuilder.java
src/test/java/org/ays/auth/model/request/AysLoginRequestBuilder.java
src/test/java/org/ays/auth/service/impl/AdminRegistrationCompleteServiceImplTest.java
src/test/java/org/ays/common/util/exception/model/response/AysErrorResponseBuilder.java
src/test/java/org/ays/emergency_application/controller/EmergencyEvacuationApplicationControllerTest.java
src/test/java/org/ays/institution/controller/InstitutionControllerTest.java
src/test/java/org/ays/util/AysValidTestData.java

AYS-421 | `@Password` Validation Annotation Has Been Created and Annotation Has Been Used for Length Limitation

---

src/main/resources/mail/template/create-password.html

AYS-353 | Update create-password.html template

---

src/main/java/org/ays/auth/model/response/AysUsersResponse.java
src/test/java/org/ays/auth/controller/AysUserEndToEndTest.java

AYS-381 | Removed UpdatedAt parameter from List Users Endpoint

---

src/main/java/org/ays/auth/service/impl/AdminRegistrationApplicationServiceImpl.java
src/main/java/org/ays/auth/service/impl/AdminRegistrationCompleteServiceImpl.java
src/main/java/org/ays/auth/service/impl/AysAuthServiceImpl.java
src/main/java/org/ays/auth/service/impl/AysInvalidTokenServiceImpl.java
src/main/java/org/ays/auth/service/impl/AysRoleCreateServiceImpl.java
src/main/java/org/ays/auth/service/impl/AysRoleUpdateServiceImpl.java
src/main/java/org/ays/auth/service/impl/AysUserCreateServiceImpl.java
src/main/java/org/ays/auth/service/impl/AysUserPasswordServiceImpl.java
src/main/java/org/ays/auth/service/impl/AysUserUpdateServiceImpl.java

AYS-297 | Usage of `@Transactional` Annotation Has Been Fixed

---

pom.xml
src/main/java/org/ays/common/util/exception/EmergencyEvacuationApplicationEndpointNotActiveException.java
src/main/java/org/ays/emergency_application/controller/EmergencyEvacuationApplicationController.java
src/main/java/org/ays/emergency_application/util/annotation/CheckEmergencyEvacuationApplicationActivity.java
src/main/java/org/ays/emergency_application/util/annotation/CheckEmergencyEvacuationApplicationActivityAspect.java
src/main/resources/application.yml

AYS-467 | Emergency Evacuation Application Endpoint Checks with AOP Annotation

---

src/main/java/org/ays/auth/service/impl/AdminRegistrationCompleteServiceImpl.java
src/main/java/org/ays/emergency_application/service/impl/EmergencyEvacuationApplicationServiceImpl.java

AYS-297 | Usage of `@Transactional` Annotations Have Been Fixed

---

src/main/java/org/ays/auth/service/impl/AysRoleUpdateServiceImpl.java
src/test/java/org/ays/auth/controller/AysRoleEndToEndTest.java
src/test/java/org/ays/auth/service/impl/AysRoleUpdateServiceImplTest.java

AYS-500 | Fixed the time and user were not being updated in the role update

---

src/main/java/org/ays/common/model/AysPageable.java

AYS-495 | The Page Size Message Changed

---

src/main/java/org/ays/auth/util/exception/AysUserNotSuperAdminException.java
src/main/java/org/ays/common/util/exception/AysForbiddenException.java
src/main/java/org/ays/common/util/exception/handler/GlobalExceptionHandler.java
src/test/java/org/ays/common/util/exception/handler/GlobalExceptionHandlerTest.java

AYS-487 | `AysUserNotSuperAdminException` Has Been Extended from `AysForbiddenException` Instead of `AccessDeniedException` Class

---

src/main/java/org/ays/auth/model/AysRole.java
src/main/java/org/ays/auth/model/entity/AysRoleEntity.java
src/main/java/org/ays/auth/service/impl/AysRoleUpdateServiceImpl.java
src/test/java/org/ays/auth/controller/AysRoleEndToEndTest.java
src/test/java/org/ays/auth/model/entity/AysRoleEntityBuilder.java

AYS-517 | Role and Permission Relations Have Been Optimized for Working Less Queries

---

src/main/java/org/ays/auth/model/AysUser.java
src/main/java/org/ays/auth/model/entity/AysUserEntity.java
src/main/java/org/ays/auth/service/impl/AysUserUpdateServiceImpl.java
src/test/java/org/ays/auth/model/entity/AysUserEntityBuilder.java

AYS-516 | User Update Flow and User-Role Relations Have Been Optimized for Working Less Queries

---

src/main/java/org/ays/auth/port/adapter/AdminRegistrationApplicationAdapter.java
src/main/java/org/ays/auth/port/adapter/AysInvalidTokenAdapter.java
src/main/java/org/ays/auth/port/adapter/AysPermissionAdapter.java
src/main/java/org/ays/auth/port/adapter/AysRoleAdapter.java
src/main/java/org/ays/auth/port/adapter/AysUserAdapter.java
src/main/java/org/ays/emergency_application/port/adapter/EmergencyEvacuationApplicationAdapter.java
src/main/java/org/ays/institution/port/adapter/InstitutionAdapter.java
src/main/java/org/ays/parameter/port/adapter/AysParameterAdapter.java
src/test/java/org/ays/auth/port/adapter/AdminRegistrationApplicationAdapterTest.java
src/test/java/org/ays/auth/port/adapter/AysInvalidTokenAdapterTest.java
src/test/java/org/ays/auth/port/adapter/AysPermissionAdapterTest.java
src/test/java/org/ays/auth/port/adapter/AysRoleAdapterTest.java
src/test/java/org/ays/auth/port/adapter/AysUserAdapterTest.java
src/test/java/org/ays/emergency_application/port/adapter/EmergencyEvacuationApplicationAdapterTest.java
src/test/java/org/ays/institution/port/adapter/InstitutionAdapterTest.java
src/test/java/org/ays/parameter/port/adapter/AysParameterAdapterTest.java

AYS-523 | `impl` Package Has Been Renamed as `adapter` in `port` Package

---

src/main/java/org/ays/common/util/validation/EmailAddressValidator.java
src/test/java/org/ays/auth/controller/AdminRegistrationApplicationControllerTest.java
src/test/java/org/ays/auth/controller/AysAuthControllerTest.java
src/test/java/org/ays/auth/controller/AysUserControllerTest.java

AYS-551 | The Email Address Validation Fixed

---

src/main/resources/application.yml

AYS-509 | `AYS_SPRING_PROFILE` Parameter Key Has Been Defined in `application.yml`

---

src/main/java/org/ays/emergency_application/model/request/EmergencyEvacuationApplicationRequest.java
src/test/java/org/ays/emergency_application/controller/EmergencyEvacuationApplicationControllerTest.java

AYS-602 | Updated EmergencyEvacuationApplicationRequest to Validate Source and Target City/District Difference

---

src/main/java/org/ays/common/service/impl/AysMailServiceImpl.java
src/test/java/org/ays/common/service/impl/AysMailServiceImplTest.java

AYS-623 | Ignored Domains Have Been Added to Mail Service for Decreasing Bounce Limit of Amazon SES

---

src/main/java/org/ays/auth/service/impl/AysUserPasswordServiceImpl.java
src/test/java/org/ays/auth/controller/AysAuthControllerTest.java
src/test/java/org/ays/auth/controller/AysAuthEndToEndTest.java
src/test/java/org/ays/auth/service/impl/AysUserPasswordServiceImplTest.java

AYS-569 | Added Institution Page permission control to forgot password service

---

src/main/java/org/ays/common/service/impl/AysMailServiceImpl.java

AYS-557 | Mail Address Changed

---

src/main/java/org/ays/common/exception/handler/GlobalExceptionHandler.java
src/test/java/org/ays/common/exception/handler/GlobalExceptionHandlerTest.java

AYS-415 |  Update 415 Error Header to Return `API_ERROR` Instead of `VALIDATION_ERROR`

---

src/main/java/org/ays/auth/port/AysRoleReadPort.java
src/main/java/org/ays/auth/port/adapter/AysRoleAdapter.java
src/main/java/org/ays/auth/repository/AysRoleRepository.java
src/main/java/org/ays/auth/service/impl/AysRoleCreateServiceImpl.java
src/main/java/org/ays/auth/service/impl/AysRoleUpdateServiceImpl.java
src/test/java/org/ays/auth/controller/AysRoleEndToEndTest.java
src/test/java/org/ays/auth/port/adapter/AysRoleAdapterTest.java
src/test/java/org/ays/auth/service/impl/AysRoleCreateServiceImplTest.java
src/test/java/org/ays/auth/service/impl/AysRoleUpdateServiceImplTest.java
src/test/java/org/ays/institution/model/InstitutionBuilder.java

AYS-640 | Create and Update Role Flows Have Been Fixed with Same Name for Different Institutions

---

src/main/java/org/ays/common/util/AysMaskUtil.java
src/test/java/org/ays/common/util/AysMaskUtilTest.java

AYS-509 | `AysMaskUtil` Has Been Refactored and Improved

---

.github/workflows/application-health-checker.yml
.github/workflows/pull-request-checker.yml
.github/workflows/test-environment-deployment.yml
.gitignore
Dockerfile
docker-compose.yml
pom.xml

AYS-656 | All Dependencies Have Been Upgraded to Latest Versions and Vulnerabilities Have Been Fixed

---

src/test/java/org/ays/common/util/AysMaskUtilTest.java

AYS-509 | `java:S5976` Sonar Warning Has Been Suppressed

---

src/main/java/org/ays/common/model/request/AysPhoneNumberRequest.java
src/test/java/org/ays/auth/controller/AdminRegistrationApplicationControllerTest.java
src/test/java/org/ays/emergency_application/controller/EmergencyEvacuationApplicationControllerTest.java
src/test/java/org/ays/util/AysMockResultMatchersBuilders.java

AYS-646 | Validation Error Format of Phone Number Has Been Refactored

---

src/main/java/org/ays/common/util/validation/PasswordValidator.java
src/test/java/org/ays/auth/controller/AdminRegistrationApplicationControllerTest.java
src/test/java/org/ays/auth/controller/AysAuthControllerTest.java

AYS-614 | Password Length Check Has Been Added

---

src/main/java/org/ays/common/util/validation/EmailAddress.java
src/main/java/org/ays/common/util/validation/EmailAddressValidator.java
src/test/java/org/ays/auth/controller/AdminRegistrationApplicationControllerTest.java
src/test/java/org/ays/auth/controller/AysAuthControllerTest.java
src/test/java/org/ays/auth/controller/AysUserControllerTest.java

AYS-674 | Email Address Validation Has Been Refactored

---

src/main/java/org/ays/common/util/AysMaskUtil.java
src/test/java/org/ays/common/util/AysMaskUtilTest.java

AYS-509 | `AysMaskUtil.mask()` Method Has Been Improved for Masking Validation Error JSONs

---

src/main/java/org/ays/auth/model/AysUserFilter.java
src/test/java/org/ays/auth/model/AysUserFilterBuilder.java
src/test/java/org/ays/auth/model/request/AysUserListRequestBuilder.java

AYS-629 | Country Code Filter Removed From The User Listing Service

---

src/main/java/org/ays/common/exception/handler/GlobalExceptionHandler.java
src/main/java/org/ays/common/model/response/AysErrorResponse.java
src/test/java/org/ays/auth/controller/AdminRegistrationApplicationEndToEndTest.java
src/test/java/org/ays/common/exception/handler/GlobalExceptionHandlerTest.java
src/test/java/org/ays/common/model/response/AysErrorResponseBuilder.java

AYS-683 | Changed 404 'NOT_FOUND' error to 'NOT_EXIST_ERROR' and updated header message to 'NOT EXIST ERROR'

---

src/main/java/org/ays/common/util/AysMaskUtil.java
src/test/java/org/ays/common/util/AysMaskUtilTest.java

AYS-509 | `AysMaskUtil.mask()` Method Has Been Fixed for Validation Errors

---

src/main/java/org/ays/auth/model/AysUserFilter.java
src/test/java/org/ays/auth/controller/AysUserControllerTest.java

AYS-681 | Adding a Length Restriction to the Phone Number Filter 

---

src/main/java/org/ays/auth/controller/AysRoleController.java
src/test/java/org/ays/auth/controller/AysRoleControllerTest.java

AYS-727 | Grant User Detail Permission for Role Summary Listing Service

---

src/main/resources/application.yml

AYS-739 | Placeholders Have Been Added for Hikari Parameters

---

src/main/java/org/ays/common/model/entity/AysAuditLogEntity.java
src/main/java/org/ays/common/repository/impl/AysAuditLogRepositoryImpl.java
src/main/java/org/ays/common/repository/impl/AysAuditLogRepositoryKinesisImpl.java
src/test/java/org/ays/common/filter/AysAuditLogFilterEndToEndTest.java
src/test/java/org/ays/common/repository/impl/AysAuditLogRepositoryImplTest.java
src/test/java/org/ays/common/repository/impl/AysAuditLogRepositoryKinesisImplTest.java
src/test/java/org/ays/common/service/impl/AysMailServiceImplTest.java

AYS-760 | Audit Log JSON Parsable Validation Has Been Added to Kinesis Implementation and Tests Have Been Improved About Logger

---

.github/workflows/pull-request-checker.yml

AYS-789 | Update PR Checker to Prevent Extra Triggers in GitHub Workflow

---

src/main/java/org/ays/auth/exception/AysUserAlreadyExistsByEmailAddressException.java
src/test/java/org/ays/auth/controller/AdminRegistrationApplicationEndToEndTest.java
src/test/java/org/ays/auth/controller/AysUserEndToEndTest.java

AYS-786 | `AysUserAlreadyExistsByEmailAddressException` Message Has Been Refactored and Email Address Has Been Masked in That Message

---

src/main/java/org/ays/auth/exception/AysUserAlreadyExistsByPhoneNumberException.java
src/test/java/org/ays/auth/controller/AdminRegistrationApplicationEndToEndTest.java
src/test/java/org/ays/auth/controller/AysUserEndToEndTest.java
src/test/java/org/ays/util/AysValidTestData.java

AYS-785 | Phone Number Has Been Masked in Exception 

---

src/main/java/org/ays/common/repository/impl/AysAuditLogRepositoryKinesisImpl.java
src/test/java/org/ays/common/repository/impl/AysAuditLogRepositoryKinesisImplTest.java

AYS-800 | `/public/actuator` Endpoints Have Been Excluded from Audit Log Saving to Kinesis

---

src/main/java/org/ays/common/exception/handler/GlobalExceptionHandler.java
src/test/java/org/ays/common/exception/handler/GlobalExceptionHandlerTest.java

AYS-801 | StackTrace Has Been Separated from Error Console Logs and StackTrace of Exception Has Been Logged on `TRACE` Log Level

---

src/main/java/org/ays/auth/config/SecurityConfiguration.java
src/main/resources/application-cors.yml
src/main/resources/application.yml

AYS-803 | CORS Has Been Configured and Parameterized

---

src/main/java/org/ays/common/repository/impl/AysAbstractAuditLogRepository.java
src/test/java/org/ays/common/filter/AysAuditLogFilterEndToEndTest.java
src/test/java/org/ays/common/repository/impl/AysAbstractAuditLogRepositoryTest.java
src/test/java/org/ays/common/repository/impl/AysAuditLogRepositoryImplTest.java

AYS-756 | Log Level of Audit Log Has Been Fixed as `info`

---

src/main/java/org/ays/common/repository/impl/AysAuditLogRepositoryKinesisImpl.java
src/test/java/org/ays/common/repository/impl/AysAuditLogRepositoryKinesisImplTest.java

AYS-814 | `429` HTTP Status Code Has Been Excluded from Kinesis Audit Log

---

src/main/java/org/ays/auth/model/mapper/AysUserEntityToDomainWithoutRelationsMapper.java
src/main/java/org/ays/auth/port/adapter/AysUserAdapter.java

AYS-787 | User List Queries Have Been Optimized

---

src/main/java/org/ays/emergency_application/model/EmergencyEvacuationApplication.java
src/main/resources/db/changelog/changes/4-ays-ddl.xml
src/test/java/org/ays/emergency_application/controller/EmergencyEvacuationApplicationEndToEndTest.java
src/test/java/org/ays/emergency_application/service/impl/EmergencyEvacuationApplicationServiceImplTest.java

AYS-609 | `EmergencyEvacuationApplication:hasObstaclePersonExist` Field Has Been Set `false` as Default

---

src/main/java/org/ays/auth/model/AysUserFilter.java
src/main/java/org/ays/common/util/validation/OnlyPositiveNumber.java
src/main/java/org/ays/common/util/validation/OnlyPositiveNumberValidator.java
src/test/java/org/ays/auth/controller/AysUserControllerTest.java
src/test/java/org/ays/util/AysMockResultMatchersBuilders.java

AYS-688 | `AysUserFilter.lineNumber` Field Validations Have Been Fixed

---

src/main/java/org/ays/common/util/validation/OnlyIntegerValidator.java

AYS-618 | `@OnlyIntegerValidator` Annotation Has Been Refactored
